name: JIRA Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  pull_request_target:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]

jobs:
  sync:
    uses: hashicorp/vault-workflows-common/.github/workflows/jira.yaml@unit-tests-workflow
    secrets:
      JIRA_SYNC_BASE_URL: ${{ secrets.JIRA_SYNC_BASE_URL }}
      JIRA_SYNC_USER_EMAIL: ${{ secrets.JIRA_SYNC_USER_EMAIL }}
      JIRA_SYNC_API_TOKEN: ${{ secrets.JIRA_SYNC_API_TOKEN }}
    with:
      teams-array: '["ecosystem", "applications"]'