name: Run Tests

on: push

jobs:
  run-unit-tests:
    uses: hashicorp/vault-workflows-common/.github/workflows/unit-tests.yaml@hack-week
  run-acc-tests:
    uses: hashicorp/vault-workflows-common/.github/workflows/acc-tests.yaml@hack-week
    secrets: inherit